"""Site data export for release 004: the JSON the ball flight page reads.

    .venv/bin/python export.py

Writes site/ball-flight/data/{model,presets,windows,ideals,camera,golden}.json
and SCHEMA.md (the SCHEMA block below: every file's keys, nested structures,
units, frame, sign, null and grid index conventions), and copies the range art to site/assets/img/004_range.jpg and
004_range_mobile.jpg (same pattern as analysis/003-augusta-12/export_site_assets.py).
Idempotent and deterministic: sorted keys, floats rounded to 6 significant
digits (model.json keeps 12 because 2 pi / 60 and the air viscosity are derived
constants, golden.json keeps 9 so the JS parity test can hold 1e-6, and
camera.json keeps every digit of the fit), no NaN, no negative zero. build()
returns the bytes without touching disk, and the tests run it twice.

Files:
  model.json    every constant and coefficient the JS port needs to recompute a
                shot: flight, launch, classify, domain.
  presets.json  clubs in order with names and groups, every preset for the three
                players, and the published table rows.
  windows.json  the 27 nine-window recipes (3 players, 7 iron), MODELED.
  ideals.json   ideal bands per club and player at the preset speed, and for the
                driver the two optimizer grids so the page can interpolate live.
  camera.json   the fitted art cameras, "wide" and "mobile".
  golden.json   the JS parity fixture: tests/golden_launch.json cases with
                classify() output, sampled trajectories for 12 of them, pure
                classify() vectors, optimal_loft() vectors and the PGA 7 iron windows.
"""

import inspect
import json
import os
import shutil
from math import isfinite

import chart
import classify
import data
import flight
import gates_launch as gl
import ideals
import launch
import presets
import windows

# The schema doc. main() writes it to site/ball-flight/data/SCHEMA.md, and a test checks the copy on
# disk matches and that every exported key is named in it.
SCHEMA = r"""# Ball flight data schema

The JSON in this folder is generated by `analysis/004-ball-flight-laws/export.py`
(`.venv/bin/python export.py`). Do not edit by hand. This file is written by the
same script from its `SCHEMA` block, so it always matches the export.

## Conventions

- **Frame.** Right-handed golfer, as seen from behind. Distances are in yards:
  `x` downrange, `y` lateral, positive RIGHT of the target line, `z` up. The page
  mirrors everything for a left-handed golfer. Nothing in the data is mirrored.
- **Signs.** Positive `path_deg` is in-to-out (right). Positive `face_deg` is
  open (right) of the target. `face_to_path_deg = face_deg - path_deg`. Positive
  `launch_dir_deg` starts right. Positive `spin_axis_deg` curves the ball right
  (fade, slice). Negative curve is left (draw, hook). `attack_deg` is positive
  for hitting up.
- **Units.** Speeds mph, angles degrees, spin rpm, distances and heights yards,
  time seconds. `model.json` constants named `_kg`, `_m`, `_ms`, `_pa_s` are SI.
- **Vocabulary.** One name per quantity in every file.
  - Delivery: `club_speed_mph`, `attack_deg`, `path_deg`, `face_deg`,
    `dyn_loft_deg`, `spin_trim` (multiplier on spin, 1.0 when absent).
  - Launch: `ball_speed_mph`, `smash`, `launch_deg`, `launch_dir_deg`,
    `spin_rpm`, `spin_axis_deg`, `spin_loft_deg`, `face_to_path_deg`.
  - Flight: `carry_yd`, `side_yd`, `curve_yd`, `max_height_yd`, `apex_x_yd`,
    `land_angle_deg`, `flight_time_s`, `land_speed_mph`, `total_yd`, and in
    `golden.json` also `land_spin_rpm` (spin left at landing, which the roll uses).
    `curve_yd = side_yd - carry_yd * tan(launch_dir_deg)`.
    `total_yd = carry_yd + roll` (roll form in `model.json` `roll.form`).
  - Ids: player ids are lowercase everywhere (`pga`, `lpga`, `amateur`). Club ids
    are `driver 3w 5w hybrid 3i 4i 5i 6i 7i 8i 9i pw`.
- **Numbers.** Floats are rounded to 6 significant digits, except `model.json`
  (12), `golden.json` (9) and `camera.json` (17, the art fit as fitted). Integers
  stay integers. No NaN, no infinity, no negative zero. Keys are sorted, so key
  order carries no meaning: use the `clubs` list or `metrics` list when you need
  an order.
- **Null and missing.** `null` in a band `lo` or `hi` means that side is open (no
  limit). A missing `published` key means no published value exists for that
  cell. `classification` is `null` in the golden fixture where `carry_yd` is 0
  (`classify` raises for a carry of zero or less, so the page must not call it
  then). `note` is an empty string when there is nothing to say. `club` is
  `null` in a golden delivery that gives no club.
- **Modeled.** Anything with `"modeled": true` is model output or a design
  choice, not a published number. Windows are always modeled and are never
  attributed to Tiger Woods.

## model.json

Everything the port needs to recompute a shot.

| Key | Contents |
|---|---|
| `note` | Text. |
| `units` | `mph_to_ms`, `yd_to_m`, `rpm_to_rads` (2 pi / 60), `g`. |
| `ball` | `mass_kg`, `diameter_m`, `radius_m`. |
| `air` | `density_kg_m3`, `viscosity_pa_s`. |
| `aero` | `quad` (`d0 d1 d2 d3 l0 l1 l2`), `re_unit`, `re_pivot`, `spin_decay_coef`, `forms` (text of CD, CL, Re, S and spin decay). |
| `roll` | `k`, `cos_power`, `spin_power`, `spin_ref_rpm`, `spin_floor_rpm`, `max_yd`, `form` (text). |
| `flight` | `dt` (0.01 s step), `max_flight_s`, `v_floor_ms`, `integrator` (`rk4`). |
| `launch_model` | `k0 k1 k_sl_lo k_sl_hi` (iron, hybrid and wood k line), `k0_driver k1_driver k_sl_lo_driver k_sl_hi_driver` (the driver's k line and its range), `smash_a smash_b smash_c smash_cap smash_floor`, `spin_a spin_b spin_f_wood` (iron spin law and the 3-wood and 5-wood factor), `spin_a_driver spin_b_driver` (the driver's spin law), `axis_c0 axis_c1 axis_sl_lo axis_sl_hi` (spin axis scale, linear in spin loft between the two bounds). |
| `spin_class` | Club id to spin class (`driver`, `wood`). The driver takes its own k line and spin law, a `wood` club the iron spin law times `spin_f_wood`, and every club not listed the iron laws. |
| `domain` | Ranges `deliver` accepts, each `[lo, hi]` inclusive: `club_speed_mph`, `attack_deg`, `path_deg`, `face_deg`, `dyn_loft_deg`, `swing_plane_deg` (open interval). `min_spin_loft_deg` is a number: `dyn_loft_deg - attack_deg` must be at least that. |
| `classify` | Thresholds: `start_straight_deg`, `axis_straight_deg`, `curve_hook_frac`, `on_target_frac`, `on_line_yd`. |
| `swing_plane_default_deg` | Default swing plane for the hold-swing-direction toggle. |

`classify` rules, in order:
1. `start`: `pull` if `launch_dir_deg < -start_straight_deg`, `push` if
   `> +start_straight_deg`, else `straight`.
2. `shape`: `straight` if `abs(spin_axis_deg) <= axis_straight_deg`. Else left
   (`draw`, `hook`) when `curve_yd < 0`, or when `curve_yd == 0` and the axis is
   negative, otherwise right (`fade`, `slice`). Left or right becomes hook or
   slice when `abs(curve_yd) > curve_hook_frac * carry_yd`, else draw or fade.
3. `on_target`: `abs(side_yd) <= on_target_frac * carry_yd`.
4. `name`: straight start gives the shape alone (`Draw`, `Slice`, `Straight`).
   Straight shape gives `Pull` or `Push`. If start and curve go opposite ways
   and `on_target`, the name is the shape alone and `worked_back` is true.
   Otherwise start plus shape (`Push draw`, `Pull hook`). First word capitalized.
5. `finish_text`: `finishes on line` when `abs(side_yd) < on_line_yd`, else
   `finishes N yd left|right` with `N = floor(abs(side_yd) + 0.5)`.
6. Inputs must be finite and `carry_yd > 0`.

## presets.json

| Key | Contents |
|---|---|
| `clubs` | Ordered list (longest club first) of `{id, name, group}`. |
| `groups` | Ordered list of `{id, name}`: `driver`, `wood`, `long_iron`, `short_iron`, `wedge`. |
| `players` | Ordered list of `{id, name}`. |
| `presets` | `presets[player][club]`, see below. |
| `driver_ideal` | `data.DRIVER_IDEAL`: `attack_deg` (5), `attack_lo_deg` (2), `attack_hi_deg` (5), `dyn_loft_half_deg` (1.5), `spin_trim` (1.0), `label`. MODELED design choice from the TrackMan 2010 charts. |
| `published` | `published[player][club]`, the table row, see below. |
| `published_note` | Text. |

`presets[player][club]`: `club_speed_mph`, `attack_deg`, `path_deg` (0),
`face_deg` (0), `dyn_loft_deg`, `spin_trim`, `club` (the club whose row was used,
`4i` for the LPGA 3-iron), `source` (text), `modeled` (bool), `note` (text, says
so for the LPGA 3-iron), `at_preset` (`{launch: {...launch fields}, flight:
{...flight fields}}` from the model at the preset), `ideal` (below).

`presets[player][club].ideal`: the delivery the tool calls ideal, at the preset
club speed. `club_speed_mph`, `attack_deg`, `path_deg` (0), `face_deg` (0),
`dyn_loft_deg`, `spin_trim`, `club`, `label` (text), `source` (text), `modeled`
(bool), `speed_clamped` (bool, the club speed is outside the chart's 75 to 120
mph), `at_ideal` (`{launch, flight}` from the model at that delivery). For every
club but the driver it repeats the preset. For the driver it is the player's club
speed, attack `driver_ideal.attack_deg` (+5, the chart's top row), dynamic loft
`optimal_loft(club speed, attack).dyn_loft_deg` (midway between the carry and total
optimizers), path 0, face 0, spin trim `driver_ideal.spin_trim` (1.0, the chart's own
strike). For the ideal at another club speed, take the same rule at that speed:
the driver's loft moves with speed (`optimal_loft`), every other club keeps its
preset values.

`published[player][club]`: TrackMan table row with `club_speed_mph`,
`attack_deg`, `ball_speed_mph`, `smash`, `launch_deg`, `spin_rpm`,
`max_height_yd`, `land_angle_deg`, `carry_yd`. PGA and LPGA driver and 6-iron
rows also carry `dyn_loft_deg` and `spin_loft_deg`. `lpga` has no `3i`.
`amateur` has `driver`, `6i` and `pw` only, with `club_speed_mph`, `attack_deg`,
`dyn_loft_deg`, `ball_speed_mph`, `launch_deg`, `spin_rpm`, `spin_loft_deg` and
`source` (text). The 6-iron and PW amateur rows are TrackMan Optimizer defaults.

## windows.json

| Key | Contents |
|---|---|
| `modeled` | Always true. |
| `note` | Text. |
| `club` | `7i`. |
| `targets` | `heights` (`low`, `mid`, `high` multipliers of the preset peak height), `curve_frac` (`draw`, `straight`, `fade`, fraction of carry, draw negative), `side_tol_yd`, `solver_tol_yd`, `attack_per_loft`. |
| `height_lever` | Text of the rule. |
| `heights`, `shapes` | Ordered id lists. |
| `players` | `players[player]["{height}_{shape}"]`, nine windows per player. |

Window: `player`, `club`, `height`, `shape`, `modeled`, `height_lever_deg` (h:
`dyn_loft_deg = preset + h`, `attack_deg = preset + attack_per_loft * h`),
`spin_trim`, `delivery` (`club_speed_mph`, `attack_deg`, `path_deg`, `face_deg`,
`dyn_loft_deg`), `target` (`max_height_yd`, `curve_yd`, `side_yd`), `launch`,
`flight`, `classification`.

`classification` (also the `classify` output everywhere): `start`
(`pull|straight|push`), `shape` (`straight|draw|fade|hook|slice`), `name`,
`worked_back` (bool), `finish_yd` (the `side_yd`), `finish_text`.

## ideals.json

| Key | Contents |
|---|---|
| `metrics` | Ordered list of the 19 band names, the same names as everywhere else: `club_speed_mph attack_deg path_deg face_deg face_to_path_deg dyn_loft_deg spin_loft_deg ball_speed_mph smash launch_deg launch_dir_deg spin_rpm spin_axis_deg max_height_yd land_angle_deg carry_yd total_yd side_yd curve_yd`. |
| `tolerances` | The half-widths and fractions the bands use (`data.IDEAL_TOL`), for example `spin_frac`, `carry_frac`, `driver_launch_margin_deg`. |
| `sources` | `source_id` to text. The id is the metric name, plus `attack_deg_driver`, `dyn_loft_deg_driver`, `launch_deg_driver` and `spin_rpm_driver`. |
| `bands` | `bands[player][club][metric]`, see below. |
| `known_exceptions` | List of `{club, player, metric, value, lo, hi, note}`: the model's ideal preset falls outside its own band the three drivers' launch (`launch_deg`): the ideal driver launches 0.3 to 0.6 deg under its band, because the band spans the carry optimizer and PING and the ideal loft sits between the carry and total optimizers. |
| `scaling` | Text rules for the bands that move with club speed. |
| `driver` | `rule`, `attack_rule`, `default_attack_deg` (5), `launch_margin_deg`, `spin_margin_rpm`, `trackman_carry_2010`, `trackman_total_2010`, `ping_2019` (the grids below). |

Band: `lo`, `hi` (either may be `null`, open), `target`, `modeled` (bool),
`source_id`, `published` (only where a table value exists), `detail` (driver
`launch_deg` and `spin_rpm` only: `trackman_carry_2010` and `ping_2019`, each
`{launch_deg, spin_rpm}`, and `inputs` `{club_speed_mph, ball_speed_mph,
attack_deg}`).

Bands are computed at the preset club speed, and for the driver at the ideal
attack angle (`default_attack_deg`). To recompute live at club speed `v` and
attack angle `a`:
- `ball_speed_mph`: target `smash * v` (`smash` from `presets[..].at_preset.launch`),
  `lo = target * (1 - ball_speed_frac)`, `hi = target * (1 + ball_speed_frac)`.
- `carry_yd`: fly the ideal delivery at speed `v` (`presets[..].ideal`; for the
  driver the loft is `optimal_loft(v, ideal attack)` and the trim is 1.0, for every other
  club the preset with its `spin_trim`), band `carry * (1 -/+ carry_frac)`.
  `total_yd` is the same flight with the roll added, band `total * (1 -/+
  total_frac)`. `side_yd` is `+- side_frac * carry`, `curve_yd` is
  `+- curve_frac * carry`, both on that scaled carry.
- Driver `attack_deg`: `lo` `driver_ideal.attack_lo_deg`, `hi` `attack_hi_deg`,
  `target` `attack_deg`, fixed. Driver `dyn_loft_deg`: target `optimal_loft(v,
  a).dyn_loft_deg`, half-width `dyn_loft_half_deg`.
- Driver `launch_deg` and `spin_rpm`: read both grids (below) at the current
  club speed, ball speed and attack angle, then `lo = min(sources) - margin`,
  `hi = max(sources) + margin`, `target` the mean of the two.
- Every other band keeps its value at the preset club speed.

`optimal_loft(club_speed, attack)`: the mean of two lofts, `carry_loft` from the
`dyn_loft_deg` table of the `trackman_carry_2010` grid and `total_loft` from the
same table of `trackman_total_2010` (both below). Each is computed the same way.
Clamp club speed to 75 to 120 mph (`speed_clamped`). Interpolate linearly across
the two nearest club speeds for the loft at attack -5, 0 and +5, then linearly in
attack angle between those three. For an attack angle beyond -5 or +5, extend the
nearest segment's slope (`extrapolated`). `dyn_loft` is `(carry_loft + total_loft) /
2`. `golden.json` `optimal_loft_vectors` carries test vectors.

Driver grids (`driver.trackman_carry_2010`, `driver.trackman_total_2010`, `driver.ping_2019`). Each has
`source`, `layout` (text), a row axis and `attack_deg` as the column axis, both
ascending, and value tables indexed `[row index][attack index]`:
- `trackman_carry_2010` (the CARRY optimizer) and `trackman_total_2010` (the
  TOTAL optimizer): rows `club_speed_mph` (75 to 120, 10 entries), columns
  `attack_deg` (-5, 0, 5). Tables `ball_speed_mph`, `launch_deg`, `spin_rpm`,
  `carry_yd`, `total_yd`, `dyn_loft_deg`, each 10 by 3. The total grid feeds
  `optimal_loft` only, the launch and spin bands read the carry grid.
- `ping_2019`: rows `ball_speed_mph` (80 to 180, 11 entries), columns
  `attack_deg` (-10 to 10 step 2, 11 entries). Tables `launch_deg` and
  `spin_rpm`, each 11 by 11.

Interpolation: bilinear in (row value, attack angle). Clamp each input to its
axis range first, so values off the grid read the edge.

## camera.json

`wide` and `mobile`, each a verbatim copy of `art/art_camera_final.json` and
`art/art_camera_final_mobile.json` plus one added field, `published_image` (the
file name under `assets/img/`: `004_range.jpg`, `004_range_mobile.jpg`). The
copied fields are `image` (the source art name), `width`, `height`, `params`,
`formula`, `fit`, `tree_base_row`, `ground_row_by_yd`, `px_per_yd_by_yd`,
`greens`, `flights`, `checks`, `per_group_views_needed`, `views`, `view_note`,
`assumptions`. The art files use their own field names (`apex_yd`, `lateral_yd`)
and are not part of the vocabulary above.

## golden.json

The JS parity fixture. Rounded to 9 significant digits.

| Key | Contents |
|---|---|
| `note` | Text. |
| `sig_digits` | 9. |
| `dt` | Time step used for every case, 0.01. |
| `cases` | 40 cases, see below. |
| `classify_vectors` | 560 `{args: [launch_dir_deg, spin_axis_deg, curve_yd, side_yd, carry_yd], result: classification}` on a 200 yd carry. |
| `optimal_loft_vectors` | 72 `{args: [club_speed_mph, attack_deg], result: {dyn_loft_deg, carry_loft_deg, total_loft_deg, extrapolated, speed_clamped}}`: club speeds 60 to 135 and attack angles -8 to +10, inside, on and outside the charts. |
| `windows_pga_7i` | `windows_pga_7i["{height}_{shape}"]`, the PGA 7-iron windows in the `windows.json` window format. |

Case: `id`, `delivery` (`club_speed_mph`, `attack_deg`, `path_deg`, `face_deg`,
`dyn_loft_deg`, `club`, `spin_trim`), `launch` (launch fields from `deliver`),
`flight` (flight fields from `simulate` at `dt`, plus `land_spin_rpm` and `total_yd`),
`classification` (or `null` when `carry_yd` is 0), and for 12 cases `trajectory`:
`stride` (10), `indices` (step numbers 0, 10, 20 and the final landing step),
`t`, `x`, `y`, `z` (arrays aligned with `indices`, yards and seconds, `y`
positive right, the last `z` is 0).
"""

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.normpath(os.path.join(HERE, "..", "..", "site"))
DATA_DIR = os.path.join(SITE, "ball-flight", "data")
IMG_DIR = os.path.join(SITE, "assets", "img")

SIG = 6  # significant digits in presets, windows and ideals
MODEL_SIG = 12  # model.json: derived constants (2 pi / 60, viscosity) need more than 6 to keep parity
GOLDEN_SIG = 9  # golden.json: tight enough that the JS parity test can hold 1e-6
TRAJECTORY_STRIDE = 10

IMAGE_COPIES = [
    ("range_final.png", "004_range.jpg"),
    ("range_final_mobile.png", "004_range_mobile.jpg"),
]

CLUB_NAMES = {
    "driver": "Driver", "3w": "3-wood", "5w": "5-wood", "hybrid": "Hybrid", "3i": "3-iron", "4i": "4-iron",
    "5i": "5-iron", "6i": "6-iron", "7i": "7-iron", "8i": "8-iron", "9i": "9-iron", "pw": "Pitching wedge",
}
CLUB_GROUP = {
    "driver": "driver", "3w": "wood", "5w": "wood", "hybrid": "long_iron", "3i": "long_iron", "4i": "long_iron",
    "5i": "long_iron", "6i": "long_iron", "7i": "short_iron", "8i": "short_iron", "9i": "short_iron", "pw": "wedge",
}
GROUPS = [
    {"id": "driver", "name": "Driver"},
    {"id": "wood", "name": "Woods"},
    {"id": "long_iron", "name": "Long irons"},
    {"id": "short_iron", "name": "Short irons"},
    {"id": "wedge", "name": "Wedge"},
]
PLAYER_NAMES = {"pga": "PGA Tour", "lpga": "LPGA Tour", "amateur": "Average amateur"}

# 12 golden cases that also carry a sampled trajectory.
TRAJECTORY_CASES = (
    "preset_pga_driver", "preset_pga_7i", "preset_pga_pw", "preset_lpga_3w", "preset_amateur_7i",
    "golfer_straight", "golfer_push_draw", "golfer_left_left", "golfer_push_slice", "golfer_pull_hook",
    "curvature_pga_driver_+5", "edge_slow_7i",
)


# ---------------------------------------------------------------------------
# JSON helpers
# ---------------------------------------------------------------------------


def clean(obj, sig=SIG):
    """Recursively round floats to `sig` significant digits, turn tuples into
    lists and keys into strings, and reject NaN and infinity. Negative zero
    becomes zero, and so does anything under 1e-12."""
    if isinstance(obj, bool) or obj is None or isinstance(obj, (int, str)):
        return obj
    if isinstance(obj, float):
        if not isfinite(obj):
            raise ValueError(f"non-finite value in export: {obj!r}")
        if abs(obj) < 1e-12:
            return 0.0  # solver noise such as 1.5e-15 yd of side
        return float(f"{obj:.{sig}g}") + 0.0
    if isinstance(obj, dict):
        return {str(k): clean(v, sig) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [clean(v, sig) for v in obj]
    raise TypeError(f"cannot export {type(obj).__name__}")


def dumps(obj):
    return (json.dumps(obj, sort_keys=True, separators=(",", ":"), allow_nan=False) + "\n").encode("utf-8")


# ---------------------------------------------------------------------------
# model.json
# ---------------------------------------------------------------------------


def build_model():
    dt = inspect.signature(flight.simulate).parameters["dt"].default
    return {
        "note": "Constants the JS port needs to recompute a shot. Frame: x downrange, y right (output), z up. "
                "Positive spin axis curves right. Everything modeled unless data.py says sourced.",
        "units": {"mph_to_ms": data.MPH_TO_MS, "yd_to_m": data.YD_TO_M, "rpm_to_rads": data.RPM_TO_RADS, "g": data.G},
        "ball": {"mass_kg": data.BALL_MASS_KG, "diameter_m": data.BALL_DIAMETER_M, "radius_m": data.BALL_RADIUS_M},
        "air": {"density_kg_m3": data.AIR_DENSITY_KG_M3, "viscosity_pa_s": data.AIR_VISCOSITY_PA_S},
        "aero": {
            "quad": dict(data.QUAD),
            "re_unit": data.RE_UNIT,
            "re_pivot": data.RE_PIVOT,
            "spin_decay_coef": data.SPIN_DECAY_COEF,
            "forms": "CD = d0 + d1 S + d2 S^2 + d3 (Re/1e5 - re_pivot); CL = l0 + l1 S + l2 S^2; S = R w / v; "
                     "Re = density v D / viscosity; dw/dt = -spin_decay_coef v w / R",
        },
        "roll": {
            "k": data.ROLL_K, "cos_power": data.ROLL_COS_POWER, "spin_power": data.ROLL_SPIN_POWER,
            "spin_ref_rpm": data.ROLL_SPIN_REF_RPM, "spin_floor_rpm": data.ROLL_SPIN_FLOOR_RPM, "max_yd": data.ROLL_MAX_YD,
            "form": "roll_yd = clamp(k * land_speed_mph * cos(land_angle)^cos_power * "
                    "(spin_ref_rpm / max(land_spin_rpm, spin_floor_rpm))^spin_power, 0, max_yd); "
                    "land_spin_rpm is the spin state at the landing step; total_yd = carry_yd + roll_yd",
        },
        "flight": {"dt": dt, "max_flight_s": flight.MAX_FLIGHT_S, "v_floor_ms": flight.V_FLOOR_MS, "integrator": "rk4"},
        "launch_model": dict(data.LAUNCH_MODEL),
        "spin_class": dict(launch.SPIN_CLASS),
        "domain": {k: list(v) if isinstance(v, tuple) else v for k, v in data.DOMAIN.items()},
        "classify": dict(data.CLASSIFY),
        "swing_plane_default_deg": data.SWING_PLANE_DEG,
    }


# ---------------------------------------------------------------------------
# presets.json
# ---------------------------------------------------------------------------


DELIVERY_NAMES = {
    "club_speed": "club_speed_mph", "attack": "attack_deg", "path": "path_deg", "face": "face_deg",
    "dyn_loft": "dyn_loft_deg",
}
METRIC_NAMES = {"club_speed": "club_speed_mph", "club_path_deg": "path_deg"}  # ideals.METRICS names that change


def launch_summary(ln):
    return {k: getattr(ln, k) for k in ln.__dataclass_fields__}


def flight_summary(f):
    """The flight fields every file uses, total_yd included (carry plus roll)."""
    return {
        "carry_yd": f.carry_yd, "side_yd": f.side_yd, "curve_yd": f.curve_yd, "max_height_yd": f.max_height_yd,
        "apex_x_yd": f.apex_x_yd, "land_angle_deg": f.land_angle_deg, "flight_time_s": f.flight_time_s,
        "land_speed_mph": f.land_speed_mph, "total_yd": flight.roll(f),
    }


def _published_rows():
    """{player: {club: row}}, lowercase player ids. Dynamic and spin loft join
    the tour rows where TrackMan publishes them (driver and 6-iron)."""
    out = {}
    for player, tour in (("pga", "PGA"), ("lpga", "LPGA")):
        rows = {}
        for club, r in data.TOURS[tour].items():
            row = dict(r)
            if (tour, club) in data.DYNAMIC_LOFT_DEG:
                row["dyn_loft_deg"] = data.DYNAMIC_LOFT_DEG[(tour, club)]
                row["spin_loft_deg"] = data.SPIN_LOFT_DEG[(tour, club)]
            rows[club] = row
        out[player] = rows
    out["amateur"] = {c: dict(a) for c, a in data.AMATEUR_ANCHORS.items()}
    return out


def build_presets():
    out_presets = {}
    for player in presets.PLAYERS:
        out_presets[player] = {}
        for club in presets.CLUBS:
            p = presets.preset(club, player)
            ln, f = presets.fly(p)
            entry = {DELIVERY_NAMES.get(k, k): v for k, v in p.items() if k != "ideal"}
            entry["at_preset"] = {"launch": launch_summary(ln), "flight": flight_summary(f)}
            ideal = {DELIVERY_NAMES.get(k, k): v for k, v in p["ideal"].items()}
            ln_i, f_i = presets.fly(p["ideal"])
            ideal["at_ideal"] = {"launch": launch_summary(ln_i), "flight": flight_summary(f_i)}
            entry["ideal"] = ideal
            out_presets[player][club] = entry
    return {
        "clubs": [{"id": c, "name": CLUB_NAMES[c], "group": CLUB_GROUP[c]} for c in presets.CLUBS],
        "groups": GROUPS,
        "players": [{"id": p, "name": PLAYER_NAMES[p]} for p in presets.PLAYERS],
        "presets": out_presets,
        "driver_ideal": dict(data.DRIVER_IDEAL),
        "published": _published_rows(),
        "published_note": "PGA and LPGA rows are the TrackMan 2023 tables (Anchors 1 and 2). LPGA has no 3-iron. "
                          "Amateur rows exist for the driver (Combine) and the 6-iron and PW (Optimizer defaults, "
                          "model output). dyn_loft_deg and spin_loft_deg are published for the driver and 6-iron only.",
    }


# ---------------------------------------------------------------------------
# windows.json
# ---------------------------------------------------------------------------


def _all_windows():
    return {player: windows.nine_windows(player) for player in presets.PLAYERS}


def build_windows(all_windows):
    return {
        "modeled": True,
        "note": "Nine-window recipes are model output. Anchor 6 anchors the concept and name only: no source "
                "publishes numbers for any window. Do not attribute them to Tiger Woods.",
        "club": data.WINDOWS["club"],
        "targets": {k: v for k, v in data.WINDOWS.items() if k != "club"},
        "height_lever": "dyn_loft = preset dyn_loft + h; attack = preset attack + attack_per_loft * h",
        "heights": list(windows.HEIGHTS),
        "shapes": list(windows.SHAPES),
        "players": {p: {f"{w['height']}_{w['shape']}": w for w in ws} for p, ws in all_windows.items()},
    }


# ---------------------------------------------------------------------------
# ideals.json
# ---------------------------------------------------------------------------


def _driver_source_text(what, margin, unit):
    return (f"TrackMan Carry Optimizer 2010 and PING 2019, read at the current club speed, ball speed and attack "
            f"angle (values in detail). Band runs from the lower source minus {margin:g} {unit} to the higher plus "
            f"{margin:g} {unit} (MODELED margin).")


def _split_sources(bands):
    """Move each band's source string into a shared sources dict. Returns
    (sources, bands) where every band has source_id and no source. The source
    id is the exported metric name, with a driver id for the two optimizer
    metrics. The text must be identical for every band that uses an id."""
    sources = {}
    tol = data.IDEAL_TOL
    out = {}
    for player, clubs in bands.items():
        out[player] = {}
        for club, metrics in clubs.items():
            out[player][club] = {}
            for metric, band in metrics.items():
                name = METRIC_NAMES.get(metric, metric)
                band = dict(band)
                text = band.pop("source")
                sid = name
                if club == "driver" and metric in ("attack_deg", "dyn_loft_deg"):
                    sid = name + "_driver"
                    text = ideals.DRIVER_ATTACK_SOURCE if metric == "attack_deg" else ideals.DRIVER_LOFT_SOURCE
                if club == "driver" and metric in ("launch_deg", "spin_rpm"):
                    sid = name + "_driver"
                    text = _driver_source_text(
                        metric, tol["driver_launch_margin_deg"] if metric == "launch_deg" else tol["driver_spin_margin_rpm"],
                        "deg" if metric == "launch_deg" else "rpm")
                if sources.setdefault(sid, text) != text:
                    raise RuntimeError(f"source text for {sid} differs between bands")
                band["source_id"] = sid
                out[player][club][name] = band
    return sources, out


def build_ideals():
    bands = {p: {c: ideals.ideal_bands(c, p) for c in presets.CLUBS} for p in presets.PLAYERS}
    sources, bands = _split_sources(bands)
    grids = ideals.optimizer_grids()
    return {
        "metrics": [METRIC_NAMES.get(m, m) for m in ideals.METRICS],
        "tolerances": dict(data.IDEAL_TOL),
        "sources": sources,
        "bands": bands,
        "known_exceptions": [
            dict(e, metric=METRIC_NAMES.get(e["metric"], e["metric"]),
                 note="Model ideal delivery (path 0, face 0) falls outside its own band. The driver's ideal loft "
                      "sits between the carry and total optimizers, so it launches a little below a band built from "
                      "the carry optimizer and PING.")
            for e in ideals.exceptions()
        ],
        "scaling": {
            "note": "Bands are computed at the preset club speed and attack angle. Two families move with the "
                    "player's club speed, and the page recomputes them live with the model.",
            "ball_speed_mph": "target = smash * club_speed, half-width ball_speed_frac of the target",
            "carry_yd": "simulate the ideal delivery at the current club speed (`ideal_delivery`; the preset for "
                        "every club but the driver) with its spin trim, half-width carry_frac of that carry",
            "total_yd": "same flight, carry plus roll (`roll` in model.json), half-width total_frac of that total",
            "driver_dyn_loft_deg": "target = optimal_loft(current club speed, current attack angle) from the TrackMan "
                                   "2010 CARRY and TOTAL grids (the mean of the two lofts), half-width `driver_ideal.dyn_loft_half_deg` "
                                   "(presets.json)",
            "side_yd_curve_yd": "half-width side_frac and curve_frac of the scaled carry",
            "fixed": "Every other band keeps its preset-speed value. Open sides are null.",
        },
        "driver": {
            "rule": "launch band = [min(sources) - margin, max(sources) + margin]; same for spin. Sources are "
                    "read by bilinear interpolation clamped to each grid: TrackMan at (club speed, attack angle), "
                    "PING at (ball speed of the ideal delivery at that club speed, attack angle).",
            "attack_rule": "attack_deg band lo = driver_ideal.attack_lo_deg, hi = attack_hi_deg, target = attack_deg "
                           "(presets.json driver_ideal), fixed for every player and club speed. All other clubs keep "
                           "preset attack +- tolerances.attack_deg.",
            "default_attack_deg": data.DRIVER_IDEAL["attack_deg"],
            "launch_margin_deg": data.IDEAL_TOL["driver_launch_margin_deg"],
            "spin_margin_rpm": data.IDEAL_TOL["driver_spin_margin_rpm"],
            **grids,
        },
    }


# ---------------------------------------------------------------------------
# camera.json
# ---------------------------------------------------------------------------


def build_camera():
    def load(name):
        with open(os.path.join(HERE, "art", name), encoding="utf-8") as fh:
            return json.load(fh)

    published = dict(IMAGE_COPIES)  # source image name -> published name under site/assets/img
    out = {"wide": load("art_camera_final.json"), "mobile": load("art_camera_final_mobile.json")}
    for cam in out.values():
        cam["published_image"] = published[cam["image"]]
    return out


# ---------------------------------------------------------------------------
# golden.json
# ---------------------------------------------------------------------------


def _trajectory(f):
    n = len(f.t)
    idx = list(range(0, n, TRAJECTORY_STRIDE))
    if idx[-1] != n - 1:
        idx.append(n - 1)  # always keep the landing sample
    return {
        "stride": TRAJECTORY_STRIDE,
        "indices": idx,
        "t": [float(f.t[i]) for i in idx],
        "x": [float(f.x[i]) for i in idx],
        "y": [float(f.y[i]) for i in idx],
        "z": [float(f.z[i]) for i in idx],
    }


def _classify_vectors():
    """Pure classify() vectors on a 200 yd carry for the JS classifier: every
    start, shape and finish (on target and off) plus the threshold edges."""
    shapes = ((0.0, 0.0), (-5.0, -10.0), (5.0, 10.0), (-10.0, -32.0), (10.0, 32.0), (1.9, 40.0), (-2.0, -10.0), (2.0001, 10.0))
    starts = (-3.0, -2.0001, -2.0, 0.0, 2.0, 2.0001, 3.0)
    sides = (-40.0, -8.5, -8.0, -2.0, 0.0, 0.9, 1.0, 8.0, 8.5, 40.0)
    out = []
    for start in starts:
        for axis, curve in shapes:
            for side in sides:
                args = [start, axis, curve, side, 200.0]
                out.append({"args": args, "result": classify.classify(*args)})
    return out


def _optimal_loft_vectors():
    """optimal_loft() at club speeds inside, on and outside the chart's 75 to 120
    mph and attack angles inside, on and outside its -5 to +5, for the JS port."""
    out = []
    for speed in (60.0, 75.0, 82.5, 94.0, 100.0, 115.0, 120.0, 135.0):
        for attack in (-8.0, -5.0, -2.5, 0.0, 2.0, 4.0, 5.0, 7.5, 10.0):
            r = chart.optimal_loft(speed, attack)
            out.append({"args": [speed, attack], "result": {
                "dyn_loft_deg": r.dyn_loft_deg, "carry_loft_deg": r.carry_loft_deg, "total_loft_deg": r.total_loft_deg,
                "extrapolated": r.extrapolated, "speed_clamped": r.speed_clamped}})
    return out


def build_golden(all_windows):
    with open(gl.GOLDEN_PATH, encoding="utf-8") as fh:
        base = json.load(fh)
    cases = []
    for case in base["cases"]:
        speed, attack, path, face, dyn_loft, club = case["args"]
        trim = case["kwargs"].get("spin_trim", 1.0)
        ln = launch.deliver(speed, attack, path, face, dyn_loft, club, spin_trim=trim)
        f = flight.simulate(ln.ball_speed_mph, ln.launch_deg, ln.launch_dir_deg, ln.spin_rpm, ln.spin_axis_deg, dt=base["dt"])
        entry = {
            "id": case["id"],
            "delivery": {"club_speed_mph": speed, "attack_deg": attack, "path_deg": path, "face_deg": face,
                         "dyn_loft_deg": dyn_loft, "club": club, "spin_trim": trim},
            "launch": case["launch"],
            "flight": dict(case["flight"], total_yd=flight.roll(f)),
            # classify() raises for a carry of zero (edge_loft_zero launches downward), so the fixture holds null.
            "classification": (classify.classify(ln.launch_dir_deg, ln.spin_axis_deg, f.curve_yd, f.side_yd, f.carry_yd)
                               if f.carry_yd > 0.0 else None),
        }
        if case["id"] in TRAJECTORY_CASES:
            entry["trajectory"] = _trajectory(f)
        cases.append(entry)
    have = {c["id"] for c in cases if "trajectory" in c}
    if have != set(TRAJECTORY_CASES):
        raise RuntimeError(f"trajectory cases missing from golden_launch.json: {sorted(set(TRAJECTORY_CASES) - have)}")
    return {
        "note": "JS parity fixture. cases: tests/golden_launch.json deliveries, launch outputs and flight summaries "
                "(total_yd added), classify() output for every case and sampled trajectories (steps 0, 10, 20 and "
                "the landing step) for 12. classify_vectors: pure classify() inputs (launch dir, spin axis, curve, "
                "side, carry) and outputs. optimal_loft_vectors: chart.optimal_loft inputs and outputs. Rounded to 9 significant digits. windows_pga_7i: the nine PGA 7-iron "
                "recipes.",
        "sig_digits": GOLDEN_SIG,
        "dt": base["dt"],
        "cases": cases,
        "classify_vectors": _classify_vectors(),
        "optimal_loft_vectors": _optimal_loft_vectors(),
        "windows_pga_7i": {f"{w['height']}_{w['shape']}": w for w in all_windows["pga"]},
    }


# ---------------------------------------------------------------------------
# Build and write
# ---------------------------------------------------------------------------


def build():
    """{filename: bytes} for every JSON file. No disk access beyond reading inputs."""
    all_windows = _all_windows()
    return {
        "model.json": dumps(clean(build_model(), MODEL_SIG)),
        "presets.json": dumps(clean(build_presets())),
        "windows.json": dumps(clean(build_windows(all_windows))),
        "ideals.json": dumps(clean(build_ideals())),
        "camera.json": dumps(clean(build_camera(), 17)),  # 17 digits keeps every double, drops -0.0
        "golden.json": dumps(clean(build_golden(all_windows), GOLDEN_SIG)),
    }


def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(IMG_DIR, exist_ok=True)
    for name, blob in build().items():
        path = os.path.join(DATA_DIR, name)
        with open(path, "wb") as fh:
            fh.write(blob)
        print(f"wrote {name} ({len(blob)} bytes)")
    with open(os.path.join(DATA_DIR, "SCHEMA.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(SCHEMA)
    print("wrote SCHEMA.md")
    for src_name, dst_name in IMAGE_COPIES:
        src = os.path.join(HERE, "art", src_name)
        dst = os.path.join(IMG_DIR, dst_name)
        shutil.copyfile(src, dst)
        print(f"copied {src_name} -> {dst}")


if __name__ == "__main__":
    main()
